services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: test-backend-torres_app-network
